httplog:
  package: 'httplog'
  fileName: 'http.log'
  maxSize: 1mb
  maxFiles: 7
  rotationFrequency: 1h
  logWriteInterval: 1s
  tail: true
rest: true
graphql: true
graphqlSchema:
  files: schema.graphql
jsResource:
  files: resources.js
